#!/bin/bash

echo "Permainan Tebak Angka"

angka=$(shuf -i 1-30 -n 1)

while true
do
        read -p "Tebak Angka 1-30 :" tebak
        if [[ $angka -eq $tebak ]]
        then
                echo "Tebakan Benar"
        break
        elif [[ $tebak -lt $angka ]]; then
                echo "Angka terlalu kecil, coba lagi"
        else
                echo "Angka terlalu besar, coba lagi"
        fi
done
